"""empty message

Revision ID: 68ff22e10145
Revises: None
Create Date: 2016-04-07 18:08:51.630000

"""

# revision identifiers, used by Alembic.
revision = '68ff22e10145'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('product_name')
    )
    op.create_table('state',
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.String(length=120), nullable=False),
    sa.Column('tax_percent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('state_id'),
    sa.UniqueConstraint('state_name')
    )
    op.create_table('buyer',
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('buyer_name', sa.String(length=120), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], [u'state.state_id'], ),
    sa.PrimaryKeyConstraint('buyer_id'),
    sa.UniqueConstraint('buyer_name')
    )
    op.create_index(op.f('ix_buyer_state_id'), 'buyer', ['state_id'], unique=False)
    op.create_table('seller',
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('seller_name', sa.String(length=120), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], [u'state.state_id'], ),
    sa.PrimaryKeyConstraint('seller_id'),
    sa.UniqueConstraint('seller_name')
    )
    op.create_index(op.f('ix_seller_state_id'), 'seller', ['state_id'], unique=False)
    op.create_table('selling',
    sa.Column('selling_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], [u'product.product_id'], ),
    sa.ForeignKeyConstraint(['seller_id'], [u'seller.seller_id'], ),
    sa.PrimaryKeyConstraint('selling_id')
    )
    op.create_index(op.f('ix_selling_product_id'), 'selling', ['product_id'], unique=False)
    op.create_index(op.f('ix_selling_seller_id'), 'selling', ['seller_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_selling_seller_id'), table_name='selling')
    op.drop_index(op.f('ix_selling_product_id'), table_name='selling')
    op.drop_table('selling')
    op.drop_index(op.f('ix_seller_state_id'), table_name='seller')
    op.drop_table('seller')
    op.drop_index(op.f('ix_buyer_state_id'), table_name='buyer')
    op.drop_table('buyer')
    op.drop_table('state')
    op.drop_table('product')
    ### end Alembic commands ###
